<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.2 on win32)" generated="2024-10-14T11:53:34.069451" rpa="false" schemaversion="5">
<suite id="s1" name="Test Post User Ddt" source="c:\iterasys\F140\Lista de excercicios 11\__tests__\test_post_user_ddt.robot">
<test id="s1-t1" name="TC01" line="8">
<status status="FAIL" start="2024-10-14T11:53:34.292255" elapsed="0.004438">Test cannot be empty.</status>
</test>
<status status="FAIL" start="2024-10-14T11:53:34.075057" elapsed="0.224194"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Post User Ddt">Test Post User Ddt</stat>
</suite>
</statistics>
<errors>
<msg time="2024-10-14T11:53:34.288245" level="ERROR">[ DataDriver ] Error in robot file:
  File "c:\iterasys\F140\Lista de excercicios 11\__tests__\test_post_user_ddt.robot", line 0</msg>
<msg time="2024-10-14T11:53:34.289204" level="ERROR">In source file:
  File "c:\iterasys\F140\Lista de excercicios 11\__tests__\..\fixtures\csv\users.csv", line 0</msg>
<msg time="2024-10-14T11:53:34.292255" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ValueError: Unassigned requiered argument detected: ${id}.</msg>
</errors>
</robot>
